#!/usr/bin/env python
 
import sys

import curses

curses.setupterm()

green = curses.tparm(curses.tigetstr("setaf"), 2).decode('utf-8')
end = curses.tigetstr("sgr0").decode('utf-8')

state = 0

for line in sys.stdin:
    line = line.rstrip()

    if state == 0:
        if line.startswith("@@"):
            state = 1
        continue

    if state == 1:
        if line.startswith("+"):
            print(green + line[1:] + end)
        else:
            print(line[1:])
