// If you modify this file, you'll need to rerun 'make proto'!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: pkg/color/color.proto

package color

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ColorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           int32                  `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Column        int32                  `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColorRequest) Reset() {
	*x = ColorRequest{}
	mi := &file_pkg_color_color_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorRequest) ProtoMessage() {}

func (x *ColorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_color_color_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorRequest.ProtoReflect.Descriptor instead.
func (*ColorRequest) Descriptor() ([]byte, []int) {
	return file_pkg_color_color_proto_rawDescGZIP(), []int{0}
}

func (x *ColorRequest) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *ColorRequest) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

type ColorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Color         string                 `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	Rate          string                 `protobuf:"bytes,2,opt,name=rate,proto3" json:"rate,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColorResponse) Reset() {
	*x = ColorResponse{}
	mi := &file_pkg_color_color_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorResponse) ProtoMessage() {}

func (x *ColorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_color_color_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorResponse.ProtoReflect.Descriptor instead.
func (*ColorResponse) Descriptor() ([]byte, []int) {
	return file_pkg_color_color_proto_rawDescGZIP(), []int{1}
}

func (x *ColorResponse) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ColorResponse) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

func (x *ColorResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ColorUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Which         string                 `protobuf:"bytes,1,opt,name=which,proto3" json:"which,omitempty"`
	Color         string                 `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColorUpdate) Reset() {
	*x = ColorUpdate{}
	mi := &file_pkg_color_color_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColorUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorUpdate) ProtoMessage() {}

func (x *ColorUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_color_color_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorUpdate.ProtoReflect.Descriptor instead.
func (*ColorUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_color_color_proto_rawDescGZIP(), []int{2}
}

func (x *ColorUpdate) GetWhich() string {
	if x != nil {
		return x.Which
	}
	return ""
}

func (x *ColorUpdate) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type ColorUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Which         string                 `protobuf:"bytes,1,opt,name=which,proto3" json:"which,omitempty"`
	Color         string                 `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColorUpdateResponse) Reset() {
	*x = ColorUpdateResponse{}
	mi := &file_pkg_color_color_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColorUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorUpdateResponse) ProtoMessage() {}

func (x *ColorUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_color_color_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorUpdateResponse.ProtoReflect.Descriptor instead.
func (*ColorUpdateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_color_color_proto_rawDescGZIP(), []int{3}
}

func (x *ColorUpdateResponse) GetWhich() string {
	if x != nil {
		return x.Which
	}
	return ""
}

func (x *ColorUpdateResponse) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

// Empty request used by GetChaos — no import needed for a local empty message.
type ChaosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChaosRequest) Reset() {
	*x = ChaosRequest{}
	mi := &file_pkg_color_color_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaosRequest) ProtoMessage() {}

func (x *ChaosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_color_color_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaosRequest.ProtoReflect.Descriptor instead.
func (*ChaosRequest) Descriptor() ([]byte, []int) {
	return file_pkg_color_color_proto_rawDescGZIP(), []int{4}
}

type ChaosState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorFraction int32                  `protobuf:"varint,1,opt,name=error_fraction,json=errorFraction,proto3" json:"error_fraction,omitempty"`
	LatchFraction int32                  `protobuf:"varint,2,opt,name=latch_fraction,json=latchFraction,proto3" json:"latch_fraction,omitempty"`
	MaxRate       float32                `protobuf:"fixed32,3,opt,name=max_rate,json=maxRate,proto3" json:"max_rate,omitempty"`
	DelayBuckets  []int32                `protobuf:"varint,4,rep,packed,name=delay_buckets,json=delayBuckets,proto3" json:"delay_buckets,omitempty"`
	Latched       bool                   `protobuf:"varint,5,opt,name=latched,proto3" json:"latched,omitempty"`
	ForceUnlatch  bool                   `protobuf:"varint,6,opt,name=force_unlatch,json=forceUnlatch,proto3" json:"force_unlatch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChaosState) Reset() {
	*x = ChaosState{}
	mi := &file_pkg_color_color_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaosState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaosState) ProtoMessage() {}

func (x *ChaosState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_color_color_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaosState.ProtoReflect.Descriptor instead.
func (*ChaosState) Descriptor() ([]byte, []int) {
	return file_pkg_color_color_proto_rawDescGZIP(), []int{5}
}

func (x *ChaosState) GetErrorFraction() int32 {
	if x != nil {
		return x.ErrorFraction
	}
	return 0
}

func (x *ChaosState) GetLatchFraction() int32 {
	if x != nil {
		return x.LatchFraction
	}
	return 0
}

func (x *ChaosState) GetMaxRate() float32 {
	if x != nil {
		return x.MaxRate
	}
	return 0
}

func (x *ChaosState) GetDelayBuckets() []int32 {
	if x != nil {
		return x.DelayBuckets
	}
	return nil
}

func (x *ChaosState) GetLatched() bool {
	if x != nil {
		return x.Latched
	}
	return false
}

func (x *ChaosState) GetForceUnlatch() bool {
	if x != nil {
		return x.ForceUnlatch
	}
	return false
}

var File_pkg_color_color_proto protoreflect.FileDescriptor

const file_pkg_color_color_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/color/color.proto\"8\n" +
	"\fColorRequest\x12\x10\n" +
	"\x03row\x18\x01 \x01(\x05R\x03row\x12\x16\n" +
	"\x06column\x18\x02 \x01(\x05R\x06column\"Q\n" +
	"\rColorResponse\x12\x14\n" +
	"\x05color\x18\x01 \x01(\tR\x05color\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\tR\x04rate\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\"9\n" +
	"\vColorUpdate\x12\x14\n" +
	"\x05which\x18\x01 \x01(\tR\x05which\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color\"A\n" +
	"\x13ColorUpdateResponse\x12\x14\n" +
	"\x05which\x18\x01 \x01(\tR\x05which\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color\"\x0e\n" +
	"\fChaosRequest\"\xd9\x01\n" +
	"\n" +
	"ChaosState\x12%\n" +
	"\x0eerror_fraction\x18\x01 \x01(\x05R\rerrorFraction\x12%\n" +
	"\x0elatch_fraction\x18\x02 \x01(\x05R\rlatchFraction\x12\x19\n" +
	"\bmax_rate\x18\x03 \x01(\x02R\amaxRate\x12#\n" +
	"\rdelay_buckets\x18\x04 \x03(\x05R\fdelayBuckets\x12\x18\n" +
	"\alatched\x18\x05 \x01(\bR\alatched\x12#\n" +
	"\rforce_unlatch\x18\x06 \x01(\bR\fforceUnlatch2\xe2\x01\n" +
	"\fColorService\x12'\n" +
	"\x06Center\x12\r.ColorRequest\x1a\x0e.ColorResponse\x12%\n" +
	"\x04Edge\x12\r.ColorRequest\x1a\x0e.ColorResponse\x121\n" +
	"\vUpdateColor\x12\f.ColorUpdate\x1a\x14.ColorUpdateResponse\x12&\n" +
	"\bGetChaos\x12\r.ChaosRequest\x1a\v.ChaosState\x12'\n" +
	"\vUpdateChaos\x12\v.ChaosState\x1a\v.ChaosStateB.Z,github.com/BuoyantIO/faces-demo/v2/pkg/colorb\x06proto3"

var (
	file_pkg_color_color_proto_rawDescOnce sync.Once
	file_pkg_color_color_proto_rawDescData []byte
)

func file_pkg_color_color_proto_rawDescGZIP() []byte {
	file_pkg_color_color_proto_rawDescOnce.Do(func() {
		file_pkg_color_color_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_color_color_proto_rawDesc), len(file_pkg_color_color_proto_rawDesc)))
	})
	return file_pkg_color_color_proto_rawDescData
}

var file_pkg_color_color_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_color_color_proto_goTypes = []any{
	(*ColorRequest)(nil),        // 0: ColorRequest
	(*ColorResponse)(nil),       // 1: ColorResponse
	(*ColorUpdate)(nil),         // 2: ColorUpdate
	(*ColorUpdateResponse)(nil), // 3: ColorUpdateResponse
	(*ChaosRequest)(nil),        // 4: ChaosRequest
	(*ChaosState)(nil),          // 5: ChaosState
}
var file_pkg_color_color_proto_depIdxs = []int32{
	0, // 0: ColorService.Center:input_type -> ColorRequest
	0, // 1: ColorService.Edge:input_type -> ColorRequest
	2, // 2: ColorService.UpdateColor:input_type -> ColorUpdate
	4, // 3: ColorService.GetChaos:input_type -> ChaosRequest
	5, // 4: ColorService.UpdateChaos:input_type -> ChaosState
	1, // 5: ColorService.Center:output_type -> ColorResponse
	1, // 6: ColorService.Edge:output_type -> ColorResponse
	3, // 7: ColorService.UpdateColor:output_type -> ColorUpdateResponse
	5, // 8: ColorService.GetChaos:output_type -> ChaosState
	5, // 9: ColorService.UpdateChaos:output_type -> ChaosState
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_color_color_proto_init() }
func file_pkg_color_color_proto_init() {
	if File_pkg_color_color_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_color_color_proto_rawDesc), len(file_pkg_color_color_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_color_color_proto_goTypes,
		DependencyIndexes: file_pkg_color_color_proto_depIdxs,
		MessageInfos:      file_pkg_color_color_proto_msgTypes,
	}.Build()
	File_pkg_color_color_proto = out.File
	file_pkg_color_color_proto_goTypes = nil
	file_pkg_color_color_proto_depIdxs = nil
}
