// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.33.1
// source: pkg/color/color.proto

package color

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ColorServiceClient is the client API for ColorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ColorServiceClient interface {
	Center(ctx context.Context, in *ColorRequest, opts ...grpc.CallOption) (*ColorResponse, error)
	Edge(ctx context.Context, in *ColorRequest, opts ...grpc.CallOption) (*ColorResponse, error)
	UpdateColor(ctx context.Context, in *ColorUpdate, opts ...grpc.CallOption) (*ColorResponse, error)
}

type colorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewColorServiceClient(cc grpc.ClientConnInterface) ColorServiceClient {
	return &colorServiceClient{cc}
}

func (c *colorServiceClient) Center(ctx context.Context, in *ColorRequest, opts ...grpc.CallOption) (*ColorResponse, error) {
	out := new(ColorResponse)
	err := c.cc.Invoke(ctx, "/ColorService/Center", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colorServiceClient) Edge(ctx context.Context, in *ColorRequest, opts ...grpc.CallOption) (*ColorResponse, error) {
	out := new(ColorResponse)
	err := c.cc.Invoke(ctx, "/ColorService/Edge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colorServiceClient) UpdateColor(ctx context.Context, in *ColorUpdate, opts ...grpc.CallOption) (*ColorResponse, error) {
	out := new(ColorResponse)
	err := c.cc.Invoke(ctx, "/ColorService/UpdateColor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ColorServiceServer is the server API for ColorService service.
// All implementations must embed UnimplementedColorServiceServer
// for forward compatibility
type ColorServiceServer interface {
	Center(context.Context, *ColorRequest) (*ColorResponse, error)
	Edge(context.Context, *ColorRequest) (*ColorResponse, error)
	UpdateColor(context.Context, *ColorUpdate) (*ColorResponse, error)
	mustEmbedUnimplementedColorServiceServer()
}

// UnimplementedColorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedColorServiceServer struct {
}

func (UnimplementedColorServiceServer) Center(context.Context, *ColorRequest) (*ColorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Center not implemented")
}
func (UnimplementedColorServiceServer) Edge(context.Context, *ColorRequest) (*ColorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Edge not implemented")
}
func (UnimplementedColorServiceServer) UpdateColor(context.Context, *ColorUpdate) (*ColorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateColor not implemented")
}
func (UnimplementedColorServiceServer) mustEmbedUnimplementedColorServiceServer() {}

// UnsafeColorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ColorServiceServer will
// result in compilation errors.
type UnsafeColorServiceServer interface {
	mustEmbedUnimplementedColorServiceServer()
}

func RegisterColorServiceServer(s grpc.ServiceRegistrar, srv ColorServiceServer) {
	s.RegisterService(&ColorService_ServiceDesc, srv)
}

func _ColorService_Center_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ColorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColorServiceServer).Center(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ColorService/Center",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColorServiceServer).Center(ctx, req.(*ColorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColorService_Edge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ColorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColorServiceServer).Edge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ColorService/Edge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColorServiceServer).Edge(ctx, req.(*ColorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColorService_UpdateColor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ColorUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColorServiceServer).UpdateColor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ColorService/UpdateColor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColorServiceServer).UpdateColor(ctx, req.(*ColorUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

// ColorService_ServiceDesc is the grpc.ServiceDesc for ColorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ColorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ColorService",
	HandlerType: (*ColorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Center",
			Handler:    _ColorService_Center_Handler,
		},
		{
			MethodName: "Edge",
			Handler:    _ColorService_Edge_Handler,
		},
		{
			MethodName: "UpdateColor",
			Handler:    _ColorService_UpdateColor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/color/color.proto",
}
