// If you modify this file, you'll need to rerun 'make proto'!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.1
// source: pkg/color/color.proto

package color

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ColorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row    int32 `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Column int32 `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
}

func (x *ColorRequest) Reset() {
	*x = ColorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_color_color_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorRequest) ProtoMessage() {}

func (x *ColorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_color_color_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorRequest.ProtoReflect.Descriptor instead.
func (*ColorRequest) Descriptor() ([]byte, []int) {
	return file_pkg_color_color_proto_rawDescGZIP(), []int{0}
}

func (x *ColorRequest) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *ColorRequest) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

type ColorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Color  string   `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	Rate   string   `protobuf:"bytes,2,opt,name=rate,proto3" json:"rate,omitempty"`
	Errors []string `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *ColorResponse) Reset() {
	*x = ColorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_color_color_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorResponse) ProtoMessage() {}

func (x *ColorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_color_color_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorResponse.ProtoReflect.Descriptor instead.
func (*ColorResponse) Descriptor() ([]byte, []int) {
	return file_pkg_color_color_proto_rawDescGZIP(), []int{1}
}

func (x *ColorResponse) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ColorResponse) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

func (x *ColorResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ColorUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Color string `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *ColorUpdate) Reset() {
	*x = ColorUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_color_color_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColorUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorUpdate) ProtoMessage() {}

func (x *ColorUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_color_color_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorUpdate.ProtoReflect.Descriptor instead.
func (*ColorUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_color_color_proto_rawDescGZIP(), []int{2}
}

func (x *ColorUpdate) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

var File_pkg_color_color_proto protoreflect.FileDescriptor

var file_pkg_color_color_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x2f, 0x63, 0x6f, 0x6c, 0x6f,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x0c, 0x43, 0x6f, 0x6c, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x6f, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c,
	0x75, 0x6d, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x22, 0x51, 0x0a, 0x0d, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x22, 0x23, 0x0a, 0x0b, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x32, 0x8b, 0x01, 0x0a, 0x0c, 0x43, 0x6f,
	0x6c, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x43, 0x65,
	0x6e, 0x74, 0x65, 0x72, 0x12, 0x0d, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x45, 0x64, 0x67, 0x65, 0x12, 0x0d, 0x2e, 0x43, 0x6f,
	0x6c, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x43, 0x6f, 0x6c,
	0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x0b, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x0c, 0x2e, 0x43, 0x6f, 0x6c, 0x6f,
	0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x1a, 0x0e, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x42, 0x75, 0x6f, 0x79, 0x61, 0x6e, 0x74, 0x49, 0x4f, 0x2f,
	0x66, 0x61, 0x63, 0x65, 0x73, 0x2d, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x76, 0x32, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_color_color_proto_rawDescOnce sync.Once
	file_pkg_color_color_proto_rawDescData = file_pkg_color_color_proto_rawDesc
)

func file_pkg_color_color_proto_rawDescGZIP() []byte {
	file_pkg_color_color_proto_rawDescOnce.Do(func() {
		file_pkg_color_color_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_color_color_proto_rawDescData)
	})
	return file_pkg_color_color_proto_rawDescData
}

var file_pkg_color_color_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_color_color_proto_goTypes = []interface{}{
	(*ColorRequest)(nil),  // 0: ColorRequest
	(*ColorResponse)(nil), // 1: ColorResponse
	(*ColorUpdate)(nil),   // 2: ColorUpdate
}
var file_pkg_color_color_proto_depIdxs = []int32{
	0, // 0: ColorService.Center:input_type -> ColorRequest
	0, // 1: ColorService.Edge:input_type -> ColorRequest
	2, // 2: ColorService.UpdateColor:input_type -> ColorUpdate
	1, // 3: ColorService.Center:output_type -> ColorResponse
	1, // 4: ColorService.Edge:output_type -> ColorResponse
	1, // 5: ColorService.UpdateColor:output_type -> ColorResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_color_color_proto_init() }
func file_pkg_color_color_proto_init() {
	if File_pkg_color_color_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_color_color_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_color_color_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_color_color_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColorUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_color_color_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_color_color_proto_goTypes,
		DependencyIndexes: file_pkg_color_color_proto_depIdxs,
		MessageInfos:      file_pkg_color_color_proto_msgTypes,
	}.Build()
	File_pkg_color_color_proto = out.File
	file_pkg_color_color_proto_rawDesc = nil
	file_pkg_color_color_proto_goTypes = nil
	file_pkg_color_color_proto_depIdxs = nil
}
