[package]
name = "rusty"
edition = "2021"
version = "0.1.0"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasmcloud-component = "0.2.0"
rand = "0.8.5"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }