{{- if .Values.color2.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: color2
  namespace: {{ .Release.Namespace }}
  labels:
    service: color2
spec:
  type: ClusterIP
  selector:
    service: color2
  ports:
  - port: 80
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: color2
  namespace: {{ .Release.Namespace }}
  labels:
    service: color2
spec:
  replicas: 1
  selector:
    matchLabels:
      service: color2
  template:
    metadata:
      labels:
        service: color2
    spec:
      containers:
      - name: color2
        image: {{ include "partials.color2-image" . }}
        imagePullPolicy: {{ include "partials.color2-imagePullPolicy" . }}
        ports:
        - name: http
          containerPort: 8000
        env:
        - name: FACES_SERVICE
          value: "color"
        - name: USER_HEADER_NAME
          value: {{ .Values.authHeader | quote }}
        {{- if .Values.color2.color }}
        - name: COLOR
          value: {{ .Values.color2.color }}
        {{- end -}}
        {{- include "partials.color2-errorFraction" . }}
        {{- include "partials.color2-delayBuckets" . }}
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi
{{- end -}}
