{{- $name := "face" -}}
{{- if .Values.ingress.enabled -}}
  {{- $name = "cell" -}}
{{- end -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    buoyant.io/application: faces
    faces.buoyant.io/component-type: edge
    faces.buoyant.io/component: {{ $name | quote }}
spec:
  type: ClusterIP
  selector:
    buoyant.io/application: faces
    faces.buoyant.io/component-type: edge
    faces.buoyant.io/component: {{ $name | quote }}
  ports:
  - port: 80
    name: http
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    buoyant.io/application: faces
    faces.buoyant.io/component-type: edge
    faces.buoyant.io/component: {{ $name | quote }}
spec:
  replicas: {{ get .Values.face "replicas"
               | default .Values.defaultReplicas }}
  selector:
    matchLabels:
      buoyant.io/application: faces
      faces.buoyant.io/component-type: edge
      faces.buoyant.io/component: {{ $name | quote }}
  template:
    metadata:
      labels:
        buoyant.io/application: faces
        faces.buoyant.io/component-type: edge
        faces.buoyant.io/component: {{ $name | quote }}
    spec:
      {{ include "partials.face-affinityclause" . }}
      containers:
      - name: {{ $name }}
        image: {{ include "partials.face-image" . }}
        imagePullPolicy: {{ get .Values.face "imagePullPolicy"
                            | default .Values.defaultImagePullPolicy }}
        ports:
        - name: http
          containerPort: 8000
        env:
        - name: USER_HEADER_NAME
          value: {{ .Values.authHeader | quote }}
        - name: SMILEY_SERVICE
          value: {{ get .Values.face "smileyService"
                    | default "smiley"
                    | quote }}
        - name: COLOR_SERVICE
          value: {{ get .Values.face "colorService"
                    | default "color"
                    | quote }}
        {{- include "partials.face-errorFraction" . }}
        {{- include "partials.face-delayBuckets" . }}
        {{- include "partials.face-resources" . }}
