{{- $serviceType := .Values.gui.serviceType -}}
{{- if .Values.ingress.enabled -}}
  {{- $serviceType = "LoadBalancer" -}}
{{- end -}}
---
apiVersion: v1
kind: Service
metadata:
  name: faces-gui
  namespace: {{ .Release.Namespace }}
  labels:
    service: faces-gui
spec:
  type: {{ $serviceType }}
  selector:
    service: faces-gui
  ports:
  - port: 80
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: faces-gui
  namespace: {{ .Release.Namespace }}
  labels:
    service: faces-gui
spec:
  replicas: {{ include "partials.gui-replicas" . }}
  selector:
    matchLabels:
      service: faces-gui
  template:
    metadata:
      labels:
        service: faces-gui
    spec:
      {{ include "partials.gui-affinityclause" . }}
      containers:
      - name: faces-gui
        image: {{ include "partials.gui-image" . }}
        imagePullPolicy: {{ include "partials.gui-imagePullPolicy" . }}
        env:
        - name: USER_HEADER_NAME
          value: {{ .Values.authHeader | quote }}
        ports:
        - name: http
          containerPort: 8000
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
