{{- $name := "face" -}}
{{- if .Values.ingress.enabled -}}
  {{- $name = "cell" -}}
{{- end -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    service: {{ $name }}
spec:
  type: ClusterIP
  selector:
    service: {{ $name }}
  ports:
  - port: 80
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    service: {{ $name }}
spec:
  replicas: {{ include "partials.face-replicas" . }}
  selector:
    matchLabels:
      service: {{ $name }}
  template:
    metadata:
      labels:
        service: {{ $name }}
    spec:
      {{ include "partials.face-affinityclause" . }}
      containers:
      - name: {{ $name }}
        image: {{ include "partials.face-image" . }}
        imagePullPolicy: {{ include "partials.face-imagePullPolicy" . }}
        ports:
        - name: http
          containerPort: 8000
        env:
        - name: FACES_SERVICE
          value: "face"
        - name: USER_HEADER_NAME
          value: {{ .Values.authHeader | quote }}
        {{- include "partials.face-errorFraction" . }}
        {{- include "partials.face-delayBuckets" . }}
        resources:
          requests:
            cpu: 300m     # The face service doesn't need much memory, but it does need more
            memory: 64Mi  # CPU than the other backend services since it has to call the
          limits:         # face and smiley services, then composite the results.
            cpu: 500m
            memory: 128Mi
