{{- $serviceType := .Values.gui.serviceType -}}
{{- if .Values.ingress.enabled -}}
  {{- $serviceType = "LoadBalancer" -}}
{{- end -}}
---
apiVersion: v1
kind: Service
metadata:
  name: faces-gui
  namespace: {{ .Release.Namespace }}
  labels:
    buoyant.io/application: faces
    faces.buoyant.io/component-type: frontend
    faces.buoyant.io/component: faces-gui
spec:
  type: {{ $serviceType }}
  selector:
    buoyant.io/application: faces
    faces.buoyant.io/component-type: frontend
    faces.buoyant.io/component: faces-gui
  ports:
  - port: 80
    name: http
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: faces-gui
  namespace: {{ .Release.Namespace }}
  labels:
    buoyant.io/application: faces
    faces.buoyant.io/component-type: frontend
    faces.buoyant.io/component: faces-gui
spec:
  replicas: {{ include "partials.gui-replicas" . }}
  selector:
    matchLabels:
      buoyant.io/application: faces
      faces.buoyant.io/component-type: frontend
      faces.buoyant.io/component: faces-gui
  template:
    metadata:
      labels:
        buoyant.io/application: faces
        faces.buoyant.io/component-type: frontend
        faces.buoyant.io/component: faces-gui
    spec:
      {{ include "partials.gui-affinityclause" . }}
      containers:
      - name: faces-gui
        image: {{ include "partials.gui-image" . }}
        imagePullPolicy: {{ include "partials.gui-imagePullPolicy" . }}
        env:
        - name: USER_HEADER_NAME
          value: {{ .Values.authHeader | quote }}
        ports:
        - name: http
          containerPort: 8000
        {{- include "partials.gui-resources" . }}
