{{- if .Values.ingress.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: face
  namespace: {{ .Release.Namespace }}
  labels:
    buoyant.io/application: faces
    faces.buoyant.io/component-type: edge
    faces.buoyant.io/component: faces-gui
spec:
  type: ClusterIP
  selector:
    buoyant.io/application: faces
    faces.buoyant.io/component-type: edge
    faces.buoyant.io/component: faces-gui
  ports:
  - port: 80
    name: http
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: face
  namespace: {{ .Release.Namespace }}
  labels:
    buoyant.io/application: faces
    faces.buoyant.io/component-type: edge
    faces.buoyant.io/component: faces-gui
spec:
  replicas: 1
  selector:
    matchLabels:
      buoyant.io/application: faces
      faces.buoyant.io/component-type: edge
      faces.buoyant.io/component: faces-gui
  template:
    metadata:
      labels:
        buoyant.io/application: faces
        faces.buoyant.io/component-type: edge
        faces.buoyant.io/component: faces-gui
    spec:
      containers:
      - name: face
        image: {{ include "partials.ingress-image" . }}
        imagePullPolicy: {{ include "partials.ingress-imagePullPolicy" . }}
        ports:
        - name: http
          containerPort: 8000
        env:
        - name: FACES_SERVICE
          value: "ingress"
        - name: USER_HEADER_NAME
          value: {{ .Values.authHeader | quote }}
        - name: CELL_SERVICE
          value: {{ .Values.ingress.cellService | quote }}
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          # limits:
          #   cpu: 250m
          #   memory: 128Mi
{{- end -}}
