{{- if .Values.ingress.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: face
  namespace: {{ .Release.Namespace }}
  labels:
    buoyant.io/application: faces
    faces.buoyant.io/component-type: edge
    faces.buoyant.io/component: faces-gui
spec:
  type: ClusterIP
  selector:
    buoyant.io/application: faces
    faces.buoyant.io/component-type: edge
    faces.buoyant.io/component: faces-gui
  ports:
  - port: 80
    name: http
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: face
  namespace: {{ .Release.Namespace }}
  labels:
    buoyant.io/application: faces
    faces.buoyant.io/component-type: edge
    faces.buoyant.io/component: faces-gui
spec:
  replicas: {{ get .Values.ingress "replicas"
               | default .Values.defaultReplicas }}
  selector:
    matchLabels:
      buoyant.io/application: faces
      faces.buoyant.io/component-type: edge
      faces.buoyant.io/component: faces-gui
  template:
    metadata:
      labels:
        buoyant.io/application: faces
        faces.buoyant.io/component-type: edge
        faces.buoyant.io/component: faces-gui
    spec:
      containers:
      - name: face
        image: {{ include "partials.ingress-image" . }}
        imagePullPolicy: {{ get .Values.ingress "imagePullPolicy"
                            | default .Values.defaultImagePullPolicy }}
        ports:
        - name: http
          containerPort: 8000
        env:
        - name: FACES_SERVICE
          value: "ingress"
        - name: USER_HEADER_NAME
          value: {{ .Values.authHeader | quote }}
        - name: CELL_SERVICE
          value: {{ .Values.ingress.cellService | quote }}
        {{- include "partials.ingress-resources" . }}
{{- end -}}
