{{- if .Values.smiley2.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: smiley2
  namespace: {{ .Release.Namespace }}
  labels:
    service: smiley2
spec:
  type: ClusterIP
  selector:
    service: smiley2
  ports:
  - port: 80
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smiley2
  namespace: {{ .Release.Namespace }}
  labels:
    service: smiley2
spec:
  replicas: 1
  selector:
    matchLabels:
      service: smiley2
  template:
    metadata:
      labels:
        service: smiley2
    spec:
      containers:
      - name: smiley2
        image: {{ include "partials.smiley2-image" . }}
        imagePullPolicy: {{ include "partials.smiley2-imagePullPolicy" . }}
        ports:
        - name: http
          containerPort: 8000
        env:
        - name: FACES_SERVICE
          value: "smiley"
        - name: USER_HEADER_NAME
          value: {{ .Values.authHeader | quote }}
        {{- if .Values.smiley2.smiley }}
        - name: SMILEY
          value: {{ .Values.smiley2.smiley }}
        {{- end -}}
        {{- include "partials.smiley2-errorFraction" . }}
        {{- include "partials.smiley2-delayBuckets" . }}
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi
{{ end }}
